// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: buyer_briefs.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const insertBriefStatusHistory = `-- name: InsertBriefStatusHistory :exec
INSERT INTO buyer_brief_status_history (buyer_brief_id, from_status, to_status, note)
VALUES ($1, $2, $3, $4)
`

type InsertBriefStatusHistoryParams struct {
	BuyerBriefID int64
	FromStatus   *BriefStatus
	ToStatus     BriefStatus
	Note         *string
}

func (q *Queries) InsertBriefStatusHistory(ctx context.Context, arg InsertBriefStatusHistoryParams) error {
	_, err := q.db.Exec(ctx, insertBriefStatusHistory,
		arg.BuyerBriefID,
		arg.FromStatus,
		arg.ToStatus,
		arg.Note,
	)
	return err
}

const insertBuyerBrief = `-- name: InsertBuyerBrief :one
INSERT INTO buyer_briefs (
  public_token, status,
  buyer_name, buyer_phone, buyer_zalo, buyer_email, company_or_brand,
  desired_deadline, production_model, sample_required,
  preferred_province_code, preferred_district_id,
  target_price_note, general_note, source, submitted_at
) VALUES (
  $1, 'submitted',
  $2, $3, $4, $5, $6,
  $7, $8, $9,
  $10, $11,
  $12, $13, $14, now()
)
RETURNING id
`

type InsertBuyerBriefParams struct {
	PublicToken           string
	BuyerName             string
	BuyerPhone            string
	BuyerZalo             *string
	BuyerEmail            *string
	CompanyOrBrand        *string
	DesiredDeadline       pgtype.Date
	ProductionModel       *ProductionModel
	SampleRequired        *bool
	PreferredProvinceCode *string
	PreferredDistrictID   *int64
	TargetPriceNote       *string
	GeneralNote           *string
	Source                *string
}

// Tạo Buyer Brief ở trạng thái submitted (public submit). submitted_at = now().
func (q *Queries) InsertBuyerBrief(ctx context.Context, arg InsertBuyerBriefParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertBuyerBrief,
		arg.PublicToken,
		arg.BuyerName,
		arg.BuyerPhone,
		arg.BuyerZalo,
		arg.BuyerEmail,
		arg.CompanyOrBrand,
		arg.DesiredDeadline,
		arg.ProductionModel,
		arg.SampleRequired,
		arg.PreferredProvinceCode,
		arg.PreferredDistrictID,
		arg.TargetPriceNote,
		arg.GeneralNote,
		arg.Source,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertBuyerBriefItem = `-- name: InsertBuyerBriefItem :exec
INSERT INTO buyer_brief_items (
  buyer_brief_id, category_id, estimated_quantity, colors_note, material_note
) VALUES ($1, $2, $3, $4, $5)
`

type InsertBuyerBriefItemParams struct {
	BuyerBriefID      int64
	CategoryID        int64
	EstimatedQuantity int32
	ColorsNote        *string
	MaterialNote      *string
}

func (q *Queries) InsertBuyerBriefItem(ctx context.Context, arg InsertBuyerBriefItemParams) error {
	_, err := q.db.Exec(ctx, insertBuyerBriefItem,
		arg.BuyerBriefID,
		arg.CategoryID,
		arg.EstimatedQuantity,
		arg.ColorsNote,
		arg.MaterialNote,
	)
	return err
}
