// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: capabilities.sql

package sqlcgen

import (
	"context"
)

const upsertCapability = `-- name: UpsertCapability :exec
INSERT INTO profile_capabilities (
  profile_id, category_id, production_model, usual_min_order_qty, sample_supported
)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (profile_id, category_id, production_model) DO UPDATE
  SET usual_min_order_qty = EXCLUDED.usual_min_order_qty,
      sample_supported    = EXCLUDED.sample_supported
`

type UpsertCapabilityParams struct {
	ProfileID        int64
	CategoryID       int64
	ProductionModel  ProductionModel
	UsualMinOrderQty *int32
	SampleSupported  bool
}

// Dùng cho seed demo — idempotent theo (profile_id, category_id, production_model).
func (q *Queries) UpsertCapability(ctx context.Context, arg UpsertCapabilityParams) error {
	_, err := q.db.Exec(ctx, upsertCapability,
		arg.ProfileID,
		arg.CategoryID,
		arg.ProductionModel,
		arg.UsualMinOrderQty,
		arg.SampleSupported,
	)
	return err
}
