// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: categories.sql

package sqlcgen

import (
	"context"
)

const listCategories = `-- name: ListCategories :many
SELECT id, slug, name_vi
FROM categories
WHERE is_active = true
ORDER BY sort_order, name_vi
`

type ListCategoriesRow struct {
	ID     int64
	Slug   string
	NameVi string
}

func (q *Queries) ListCategories(ctx context.Context) ([]ListCategoriesRow, error) {
	rows, err := q.db.Query(ctx, listCategories)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCategoriesRow
	for rows.Next() {
		var i ListCategoriesRow
		if err := rows.Scan(&i.ID, &i.Slug, &i.NameVi); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertCategory = `-- name: UpsertCategory :exec
INSERT INTO categories (slug, name_vi, sort_order)
VALUES ($1, $2, $3)
ON CONFLICT (slug) DO UPDATE
  SET name_vi    = EXCLUDED.name_vi,
      sort_order = EXCLUDED.sort_order
`

type UpsertCategoryParams struct {
	Slug      string
	NameVi    string
	SortOrder int32
}

// Master data — idempotent theo slug. parent_id để NULL ở seed phẳng.
func (q *Queries) UpsertCategory(ctx context.Context, arg UpsertCategoryParams) error {
	_, err := q.db.Exec(ctx, upsertCategory, arg.Slug, arg.NameVi, arg.SortOrder)
	return err
}
