// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: districts.sql

package sqlcgen

import (
	"context"
)

const upsertDistrict = `-- name: UpsertDistrict :exec
INSERT INTO districts (province_code, name_vi, slug)
VALUES ($1, $2, $3)
ON CONFLICT (province_code, slug) DO UPDATE
  SET name_vi = EXCLUDED.name_vi
`

type UpsertDistrictParams struct {
	ProvinceCode string
	NameVi       string
	Slug         string
}

// Dùng cho seed master data — idempotent theo (province_code, slug).
func (q *Queries) UpsertDistrict(ctx context.Context, arg UpsertDistrictParams) error {
	_, err := q.db.Exec(ctx, upsertDistrict, arg.ProvinceCode, arg.NameVi, arg.Slug)
	return err
}
