// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: idempotency.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getIdempotencyRecord = `-- name: GetIdempotencyRecord :one
SELECT request_hash, resource_public_token, response_status
FROM idempotency_records
WHERE scope = $1 AND key_hash = $2
`

type GetIdempotencyRecordParams struct {
	Scope   string
	KeyHash string
}

type GetIdempotencyRecordRow struct {
	RequestHash         string
	ResourcePublicToken *string
	ResponseStatus      *int32
}

func (q *Queries) GetIdempotencyRecord(ctx context.Context, arg GetIdempotencyRecordParams) (GetIdempotencyRecordRow, error) {
	row := q.db.QueryRow(ctx, getIdempotencyRecord, arg.Scope, arg.KeyHash)
	var i GetIdempotencyRecordRow
	err := row.Scan(&i.RequestHash, &i.ResourcePublicToken, &i.ResponseStatus)
	return i, err
}

const insertIdempotencyRecord = `-- name: InsertIdempotencyRecord :exec
INSERT INTO idempotency_records (
  scope, key_hash, request_hash, resource_type, resource_public_token, response_status, expires_at
) VALUES ($1, $2, $3, $4, $5, $6, $7)
`

type InsertIdempotencyRecordParams struct {
	Scope               string
	KeyHash             string
	RequestHash         string
	ResourceType        *string
	ResourcePublicToken *string
	ResponseStatus      *int32
	ExpiresAt           pgtype.Timestamptz
}

func (q *Queries) InsertIdempotencyRecord(ctx context.Context, arg InsertIdempotencyRecordParams) error {
	_, err := q.db.Exec(ctx, insertIdempotencyRecord,
		arg.Scope,
		arg.KeyHash,
		arg.RequestHash,
		arg.ResourceType,
		arg.ResourcePublicToken,
		arg.ResponseStatus,
		arg.ExpiresAt,
	)
	return err
}
