// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: leads.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countLeads = `-- name: CountLeads :one
SELECT count(*) FROM leads
`

func (q *Queries) CountLeads(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLeads)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const insertLead = `-- name: InsertLead :one
INSERT INTO leads (public_token, buyer_brief_id, profile_id, brief_match_id, current_status)
VALUES ($1, $2, $3, $4, 'created')
RETURNING id
`

type InsertLeadParams struct {
	PublicToken  string
	BuyerBriefID int64
	ProfileID    int64
	BriefMatchID *int64
}

// Lead cho cặp (brief × profile). current_status khởi tạo 'created'.
func (q *Queries) InsertLead(ctx context.Context, arg InsertLeadParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertLead,
		arg.PublicToken,
		arg.BuyerBriefID,
		arg.ProfileID,
		arg.BriefMatchID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertLeadStatusHistory = `-- name: InsertLeadStatusHistory :exec
INSERT INTO lead_status_history (lead_id, from_status, to_status, note)
VALUES ($1, $2, $3, $4)
`

type InsertLeadStatusHistoryParams struct {
	LeadID     int64
	FromStatus *LeadStatus
	ToStatus   LeadStatus
	Note       *string
}

func (q *Queries) InsertLeadStatusHistory(ctx context.Context, arg InsertLeadStatusHistoryParams) error {
	_, err := q.db.Exec(ctx, insertLeadStatusHistory,
		arg.LeadID,
		arg.FromStatus,
		arg.ToStatus,
		arg.Note,
	)
	return err
}

const listLeads = `-- name: ListLeads :many
SELECT l.public_token, l.current_status, l.created_at,
       p.slug AS profile_slug, p.name AS profile_name,
       b.public_token AS brief_token
FROM leads l
JOIN profiles p ON p.id = l.profile_id
JOIN buyer_briefs b ON b.id = l.buyer_brief_id
ORDER BY l.created_at DESC, l.id DESC
LIMIT $2 OFFSET $1
`

type ListLeadsParams struct {
	PageOffset int32
	PageSize   int32
}

type ListLeadsRow struct {
	PublicToken   string
	CurrentStatus LeadStatus
	CreatedAt     pgtype.Timestamptz
	ProfileSlug   string
	ProfileName   string
	BriefToken    string
}

func (q *Queries) ListLeads(ctx context.Context, arg ListLeadsParams) ([]ListLeadsRow, error) {
	rows, err := q.db.Query(ctx, listLeads, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLeadsRow
	for rows.Next() {
		var i ListLeadsRow
		if err := rows.Scan(
			&i.PublicToken,
			&i.CurrentStatus,
			&i.CreatedAt,
			&i.ProfileSlug,
			&i.ProfileName,
			&i.BriefToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
