// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: leads.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countLeads = `-- name: CountLeads :one
SELECT count(*) FROM leads
`

func (q *Queries) CountLeads(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countLeads)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getLeadByToken = `-- name: GetLeadByToken :one
SELECT id, current_status FROM leads WHERE public_token = $1
`

type GetLeadByTokenRow struct {
	ID            int64
	CurrentStatus LeadStatus
}

func (q *Queries) GetLeadByToken(ctx context.Context, publicToken string) (GetLeadByTokenRow, error) {
	row := q.db.QueryRow(ctx, getLeadByToken, publicToken)
	var i GetLeadByTokenRow
	err := row.Scan(&i.ID, &i.CurrentStatus)
	return i, err
}

const insertLead = `-- name: InsertLead :one
INSERT INTO leads (public_token, buyer_brief_id, profile_id, brief_match_id, current_status)
VALUES ($1, $2, $3, $4, 'created')
RETURNING id
`

type InsertLeadParams struct {
	PublicToken  string
	BuyerBriefID int64
	ProfileID    int64
	BriefMatchID *int64
}

// Lead cho cặp (brief × profile). current_status khởi tạo 'created'.
func (q *Queries) InsertLead(ctx context.Context, arg InsertLeadParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertLead,
		arg.PublicToken,
		arg.BuyerBriefID,
		arg.ProfileID,
		arg.BriefMatchID,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const insertLeadStatusHistory = `-- name: InsertLeadStatusHistory :exec
INSERT INTO lead_status_history (lead_id, from_status, to_status, note)
VALUES ($1, $2, $3, $4)
`

type InsertLeadStatusHistoryParams struct {
	LeadID     int64
	FromStatus *LeadStatus
	ToStatus   LeadStatus
	Note       *string
}

func (q *Queries) InsertLeadStatusHistory(ctx context.Context, arg InsertLeadStatusHistoryParams) error {
	_, err := q.db.Exec(ctx, insertLeadStatusHistory,
		arg.LeadID,
		arg.FromStatus,
		arg.ToStatus,
		arg.Note,
	)
	return err
}

const listLeads = `-- name: ListLeads :many
SELECT l.public_token, l.current_status, l.created_at,
       p.slug AS profile_slug, p.name AS profile_name,
       b.public_token AS brief_token
FROM leads l
JOIN profiles p ON p.id = l.profile_id
JOIN buyer_briefs b ON b.id = l.buyer_brief_id
ORDER BY l.created_at DESC, l.id DESC
LIMIT $2 OFFSET $1
`

type ListLeadsParams struct {
	PageOffset int32
	PageSize   int32
}

type ListLeadsRow struct {
	PublicToken   string
	CurrentStatus LeadStatus
	CreatedAt     pgtype.Timestamptz
	ProfileSlug   string
	ProfileName   string
	BriefToken    string
}

func (q *Queries) ListLeads(ctx context.Context, arg ListLeadsParams) ([]ListLeadsRow, error) {
	rows, err := q.db.Query(ctx, listLeads, arg.PageOffset, arg.PageSize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListLeadsRow
	for rows.Next() {
		var i ListLeadsRow
		if err := rows.Scan(
			&i.PublicToken,
			&i.CurrentStatus,
			&i.CreatedAt,
			&i.ProfileSlug,
			&i.ProfileName,
			&i.BriefToken,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateLeadStatus = `-- name: UpdateLeadStatus :execrows
UPDATE leads SET
  current_status    = $1::lead_status,
  sent_at           = CASE WHEN $1::lead_status = 'sent'           AND sent_at           IS NULL THEN now() ELSE sent_at           END,
  viewed_at         = CASE WHEN $1::lead_status = 'viewed'         AND viewed_at         IS NULL THEN now() ELSE viewed_at         END,
  first_response_at = CASE WHEN $1::lead_status = 'responded'      AND first_response_at IS NULL THEN now() ELSE first_response_at END,
  quoted_at         = CASE WHEN $1::lead_status = 'quoted'         AND quoted_at         IS NULL THEN now() ELSE quoted_at         END,
  sample_started_at = CASE WHEN $1::lead_status = 'sample_started' AND sample_started_at IS NULL THEN now() ELSE sample_started_at END,
  won_at            = CASE WHEN $1::lead_status = 'won'            AND won_at            IS NULL THEN now() ELSE won_at            END,
  lost_at           = CASE WHEN $1::lead_status = 'lost'           AND lost_at           IS NULL THEN now() ELSE lost_at           END,
  expired_at        = CASE WHEN $1::lead_status = 'expired'        AND expired_at        IS NULL THEN now() ELSE expired_at        END
WHERE id = $2 AND current_status = $3::lead_status
`

type UpdateLeadStatusParams struct {
	ToStatus   LeadStatus
	ID         int64
	FromStatus LeadStatus
}

// Atomic: chỉ đổi khi current_status đúng bằng from. 0 dòng = đã đổi (race) -> 409.
// Set mốc timestamp tương ứng. Enum param cast ::lead_status (bắt buộc cho pgx bind).
func (q *Queries) UpdateLeadStatus(ctx context.Context, arg UpdateLeadStatusParams) (int64, error) {
	result, err := q.db.Exec(ctx, updateLeadStatus, arg.ToStatus, arg.ID, arg.FromStatus)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertLeadOutcome = `-- name: UpsertLeadOutcome :exec
INSERT INTO lead_outcomes (lead_id, lost_reason)
VALUES ($1, $2)
ON CONFLICT (lead_id) DO UPDATE SET lost_reason = EXCLUDED.lost_reason
`

type UpsertLeadOutcomeParams struct {
	LeadID     int64
	LostReason *LeadLostReason
}

// Ghi lý do mất lead (và các trường outcome khác sau này). Idempotent theo lead_id.
func (q *Queries) UpsertLeadOutcome(ctx context.Context, arg UpsertLeadOutcomeParams) error {
	_, err := q.db.Exec(ctx, upsertLeadOutcome, arg.LeadID, arg.LostReason)
	return err
}
