// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: matches.sql

package sqlcgen

import (
	"context"
)

const getBriefMatchID = `-- name: GetBriefMatchID :one
SELECT id FROM brief_matches
WHERE buyer_brief_id = $1 AND profile_id = $2
`

type GetBriefMatchIDParams struct {
	BuyerBriefID int64
	ProfileID    int64
}

func (q *Queries) GetBriefMatchID(ctx context.Context, arg GetBriefMatchIDParams) (int64, error) {
	row := q.db.QueryRow(ctx, getBriefMatchID, arg.BuyerBriefID, arg.ProfileID)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listBriefMatches = `-- name: ListBriefMatches :many
SELECT m.profile_id, m.match_level, m.reasons, m.concerns,
       p.slug AS profile_slug, p.name AS profile_name
FROM brief_matches m
JOIN profiles p ON p.id = m.profile_id
WHERE m.buyer_brief_id = $1
ORDER BY m.match_level, m.matched_at
`

type ListBriefMatchesRow struct {
	ProfileID   int64
	MatchLevel  MatchLevel
	Reasons     []byte
	Concerns    []byte
	ProfileSlug string
	ProfileName string
}

func (q *Queries) ListBriefMatches(ctx context.Context, buyerBriefID int64) ([]ListBriefMatchesRow, error) {
	rows, err := q.db.Query(ctx, listBriefMatches, buyerBriefID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListBriefMatchesRow
	for rows.Next() {
		var i ListBriefMatchesRow
		if err := rows.Scan(
			&i.ProfileID,
			&i.MatchLevel,
			&i.Reasons,
			&i.Concerns,
			&i.ProfileSlug,
			&i.ProfileName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertBriefMatch = `-- name: UpsertBriefMatch :one
INSERT INTO brief_matches (buyer_brief_id, profile_id, match_level, reasons, concerns)
VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (buyer_brief_id, profile_id) DO UPDATE
  SET match_level = EXCLUDED.match_level,
      reasons     = EXCLUDED.reasons,
      concerns    = EXCLUDED.concerns
RETURNING id
`

type UpsertBriefMatchParams struct {
	BuyerBriefID int64
	ProfileID    int64
	MatchLevel   MatchLevel
	Reasons      []byte
	Concerns     []byte
}

// Shortlist một xưởng cho brief. Idempotent theo (buyer_brief_id, profile_id).
func (q *Queries) UpsertBriefMatch(ctx context.Context, arg UpsertBriefMatchParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertBriefMatch,
		arg.BuyerBriefID,
		arg.ProfileID,
		arg.MatchLevel,
		arg.Reasons,
		arg.Concerns,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}
