// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlcgen

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type AvailabilityStatus string

const (
	AvailabilityStatusAvailable  AvailabilityStatus = "available"
	AvailabilityStatusLimited    AvailabilityStatus = "limited"
	AvailabilityStatusNearlyFull AvailabilityStatus = "nearly_full"
	AvailabilityStatusFull       AvailabilityStatus = "full"
	AvailabilityStatusPaused     AvailabilityStatus = "paused"
	AvailabilityStatusUnknown    AvailabilityStatus = "unknown"
)

func (e *AvailabilityStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AvailabilityStatus(s)
	case string:
		*e = AvailabilityStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for AvailabilityStatus: %T", src)
	}
	return nil
}

type NullAvailabilityStatus struct {
	AvailabilityStatus AvailabilityStatus
	Valid              bool // Valid is true if AvailabilityStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAvailabilityStatus) Scan(value interface{}) error {
	if value == nil {
		ns.AvailabilityStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AvailabilityStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAvailabilityStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AvailabilityStatus), nil
}

type BriefStatus string

const (
	BriefStatusDraft            BriefStatus = "draft"
	BriefStatusSubmitted        BriefStatus = "submitted"
	BriefStatusUnderReview      BriefStatus = "under_review"
	BriefStatusNeedsInformation BriefStatus = "needs_information"
	BriefStatusQualified        BriefStatus = "qualified"
	BriefStatusMatching         BriefStatus = "matching"
	BriefStatusMatched          BriefStatus = "matched"
	BriefStatusRejected         BriefStatus = "rejected"
	BriefStatusCancelled        BriefStatus = "cancelled"
	BriefStatusClosed           BriefStatus = "closed"
)

func (e *BriefStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = BriefStatus(s)
	case string:
		*e = BriefStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for BriefStatus: %T", src)
	}
	return nil
}

type NullBriefStatus struct {
	BriefStatus BriefStatus
	Valid       bool // Valid is true if BriefStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullBriefStatus) Scan(value interface{}) error {
	if value == nil {
		ns.BriefStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.BriefStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullBriefStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.BriefStatus), nil
}

type ContactEventType string

const (
	ContactEventTypePhoneClick       ContactEventType = "phone_click"
	ContactEventTypeZaloClick        ContactEventType = "zalo_click"
	ContactEventTypeWebsiteClick     ContactEventType = "website_click"
	ContactEventTypeViewAddress      ContactEventType = "view_address"
	ContactEventTypeBuyerBriefStart  ContactEventType = "buyer_brief_start"
	ContactEventTypeBuyerBriefSubmit ContactEventType = "buyer_brief_submit"
)

func (e *ContactEventType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ContactEventType(s)
	case string:
		*e = ContactEventType(s)
	default:
		return fmt.Errorf("unsupported scan type for ContactEventType: %T", src)
	}
	return nil
}

type NullContactEventType struct {
	ContactEventType ContactEventType
	Valid            bool // Valid is true if ContactEventType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullContactEventType) Scan(value interface{}) error {
	if value == nil {
		ns.ContactEventType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ContactEventType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullContactEventType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ContactEventType), nil
}

type ImageKind string

const (
	ImageKindProduct     ImageKind = "product"
	ImageKindFactory     ImageKind = "factory"
	ImageKindMachine     ImageKind = "machine"
	ImageKindCertificate ImageKind = "certificate"
	ImageKindOther       ImageKind = "other"
)

func (e *ImageKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ImageKind(s)
	case string:
		*e = ImageKind(s)
	default:
		return fmt.Errorf("unsupported scan type for ImageKind: %T", src)
	}
	return nil
}

type NullImageKind struct {
	ImageKind ImageKind
	Valid     bool // Valid is true if ImageKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullImageKind) Scan(value interface{}) error {
	if value == nil {
		ns.ImageKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ImageKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullImageKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ImageKind), nil
}

type LeadLostReason string

const (
	LeadLostReasonNoResponse           LeadLostReason = "no_response"
	LeadLostReasonMoqMismatch          LeadLostReason = "moq_mismatch"
	LeadLostReasonPriceMismatch        LeadLostReason = "price_mismatch"
	LeadLostReasonDeadlineMismatch     LeadLostReason = "deadline_mismatch"
	LeadLostReasonCapacityUnavailable  LeadLostReason = "capacity_unavailable"
	LeadLostReasonCapabilityMismatch   LeadLostReason = "capability_mismatch"
	LeadLostReasonBuyerCancelled       LeadLostReason = "buyer_cancelled"
	LeadLostReasonFactoryDeclined      LeadLostReason = "factory_declined"
	LeadLostReasonSelectedOtherFactory LeadLostReason = "selected_other_factory"
	LeadLostReasonOther                LeadLostReason = "other"
)

func (e *LeadLostReason) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LeadLostReason(s)
	case string:
		*e = LeadLostReason(s)
	default:
		return fmt.Errorf("unsupported scan type for LeadLostReason: %T", src)
	}
	return nil
}

type NullLeadLostReason struct {
	LeadLostReason LeadLostReason
	Valid          bool // Valid is true if LeadLostReason is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLeadLostReason) Scan(value interface{}) error {
	if value == nil {
		ns.LeadLostReason, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LeadLostReason.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLeadLostReason) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LeadLostReason), nil
}

type LeadStatus string

const (
	LeadStatusCreated       LeadStatus = "created"
	LeadStatusSent          LeadStatus = "sent"
	LeadStatusViewed        LeadStatus = "viewed"
	LeadStatusResponded     LeadStatus = "responded"
	LeadStatusQuoted        LeadStatus = "quoted"
	LeadStatusSampleStarted LeadStatus = "sample_started"
	LeadStatusWon           LeadStatus = "won"
	LeadStatusLost          LeadStatus = "lost"
	LeadStatusExpired       LeadStatus = "expired"
)

func (e *LeadStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LeadStatus(s)
	case string:
		*e = LeadStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for LeadStatus: %T", src)
	}
	return nil
}

type NullLeadStatus struct {
	LeadStatus LeadStatus
	Valid      bool // Valid is true if LeadStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLeadStatus) Scan(value interface{}) error {
	if value == nil {
		ns.LeadStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LeadStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLeadStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LeadStatus), nil
}

type MatchLevel string

const (
	MatchLevelHigh             MatchLevel = "high"
	MatchLevelMedium           MatchLevel = "medium"
	MatchLevelLow              MatchLevel = "low"
	MatchLevelInsufficientData MatchLevel = "insufficient_data"
)

func (e *MatchLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = MatchLevel(s)
	case string:
		*e = MatchLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for MatchLevel: %T", src)
	}
	return nil
}

type NullMatchLevel struct {
	MatchLevel MatchLevel
	Valid      bool // Valid is true if MatchLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullMatchLevel) Scan(value interface{}) error {
	if value == nil {
		ns.MatchLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.MatchLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullMatchLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.MatchLevel), nil
}

type ProductionModel string

const (
	ProductionModelCmt         ProductionModel = "cmt"
	ProductionModelFob         ProductionModel = "fob"
	ProductionModelOdm         ProductionModel = "odm"
	ProductionModelFullPackage ProductionModel = "full_package"
)

func (e *ProductionModel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProductionModel(s)
	case string:
		*e = ProductionModel(s)
	default:
		return fmt.Errorf("unsupported scan type for ProductionModel: %T", src)
	}
	return nil
}

type NullProductionModel struct {
	ProductionModel ProductionModel
	Valid           bool // Valid is true if ProductionModel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProductionModel) Scan(value interface{}) error {
	if value == nil {
		ns.ProductionModel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProductionModel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProductionModel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProductionModel), nil
}

type ProfileKind string

const (
	ProfileKindFactory      ProfileKind = "factory"
	ProfileKindManufacturer ProfileKind = "manufacturer"
)

func (e *ProfileKind) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProfileKind(s)
	case string:
		*e = ProfileKind(s)
	default:
		return fmt.Errorf("unsupported scan type for ProfileKind: %T", src)
	}
	return nil
}

type NullProfileKind struct {
	ProfileKind ProfileKind
	Valid       bool // Valid is true if ProfileKind is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProfileKind) Scan(value interface{}) error {
	if value == nil {
		ns.ProfileKind, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProfileKind.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProfileKind) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProfileKind), nil
}

type ProfileStatus string

const (
	ProfileStatusDraft             ProfileStatus = "draft"
	ProfileStatusPublished         ProfileStatus = "published"
	ProfileStatusTemporarilyClosed ProfileStatus = "temporarily_closed"
	ProfileStatusArchived          ProfileStatus = "archived"
)

func (e *ProfileStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ProfileStatus(s)
	case string:
		*e = ProfileStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ProfileStatus: %T", src)
	}
	return nil
}

type NullProfileStatus struct {
	ProfileStatus ProfileStatus
	Valid         bool // Valid is true if ProfileStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullProfileStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ProfileStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ProfileStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullProfileStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ProfileStatus), nil
}

type ReviewStatus string

const (
	ReviewStatusPendingVerification ReviewStatus = "pending_verification"
	ReviewStatusPendingModeration   ReviewStatus = "pending_moderation"
	ReviewStatusApproved            ReviewStatus = "approved"
	ReviewStatusRejected            ReviewStatus = "rejected"
)

func (e *ReviewStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReviewStatus(s)
	case string:
		*e = ReviewStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ReviewStatus: %T", src)
	}
	return nil
}

type NullReviewStatus struct {
	ReviewStatus ReviewStatus
	Valid        bool // Valid is true if ReviewStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReviewStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ReviewStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReviewStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReviewStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReviewStatus), nil
}

type ReviewVerificationStatus string

const (
	ReviewVerificationStatusUnverified         ReviewVerificationStatus = "unverified"
	ReviewVerificationStatusContactVerified    ReviewVerificationStatus = "contact_verified"
	ReviewVerificationStatusEngagementVerified ReviewVerificationStatus = "engagement_verified"
	ReviewVerificationStatusOrderVerified      ReviewVerificationStatus = "order_verified"
)

func (e *ReviewVerificationStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReviewVerificationStatus(s)
	case string:
		*e = ReviewVerificationStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for ReviewVerificationStatus: %T", src)
	}
	return nil
}

type NullReviewVerificationStatus struct {
	ReviewVerificationStatus ReviewVerificationStatus
	Valid                    bool // Valid is true if ReviewVerificationStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReviewVerificationStatus) Scan(value interface{}) error {
	if value == nil {
		ns.ReviewVerificationStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReviewVerificationStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReviewVerificationStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReviewVerificationStatus), nil
}

type UserRole string

const (
	UserRoleAdmin    UserRole = "admin"
	UserRoleOperator UserRole = "operator"
	UserRoleEditor   UserRole = "editor"
	UserRoleUser     UserRole = "user"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole
	Valid    bool // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type VerificationLevel string

const (
	VerificationLevelUnverified       VerificationLevel = "unverified"
	VerificationLevelContactVerified  VerificationLevel = "contact_verified"
	VerificationLevelDocumentVerified VerificationLevel = "document_verified"
	VerificationLevelOnsiteVerified   VerificationLevel = "onsite_verified"
)

func (e *VerificationLevel) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VerificationLevel(s)
	case string:
		*e = VerificationLevel(s)
	default:
		return fmt.Errorf("unsupported scan type for VerificationLevel: %T", src)
	}
	return nil
}

type NullVerificationLevel struct {
	VerificationLevel VerificationLevel
	Valid             bool // Valid is true if VerificationLevel is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVerificationLevel) Scan(value interface{}) error {
	if value == nil {
		ns.VerificationLevel, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VerificationLevel.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVerificationLevel) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VerificationLevel), nil
}

type VerificationResult string

const (
	VerificationResultPassed  VerificationResult = "passed"
	VerificationResultPartial VerificationResult = "partial"
	VerificationResultFailed  VerificationResult = "failed"
)

func (e *VerificationResult) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = VerificationResult(s)
	case string:
		*e = VerificationResult(s)
	default:
		return fmt.Errorf("unsupported scan type for VerificationResult: %T", src)
	}
	return nil
}

type NullVerificationResult struct {
	VerificationResult VerificationResult
	Valid              bool // Valid is true if VerificationResult is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullVerificationResult) Scan(value interface{}) error {
	if value == nil {
		ns.VerificationResult, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.VerificationResult.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullVerificationResult) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.VerificationResult), nil
}

type AdminAuditLog struct {
	ID          int64
	ActorUserID *int64
	Action      string
	EntityType  string
	EntityID    *int64
	BeforeData  []byte
	AfterData   []byte
	CreatedAt   pgtype.Timestamptz
}

type BriefMatch struct {
	ID            int64
	BuyerBriefID  int64
	ProfileID     int64
	MatchLevel    MatchLevel
	Reasons       []byte
	Concerns      []byte
	MatchedBy     *int64
	MatchedAt     pgtype.Timestamptz
	BuyerAccepted *bool
	BuyerFeedback *string
}

type BuyerBrief struct {
	ID                    int64
	PublicToken           string
	Status                BriefStatus
	BuyerName             string
	BuyerPhone            string
	BuyerZalo             *string
	BuyerEmail            *string
	CompanyOrBrand        *string
	DesiredDeadline       pgtype.Date
	ProductionModel       *ProductionModel
	SampleRequired        *bool
	PreferredProvinceCode *string
	PreferredDistrictID   *int64
	TargetPriceNote       *string
	GeneralNote           *string
	Source                *string
	AssignedTo            *int64
	SubmittedAt           pgtype.Timestamptz
	ReviewedAt            pgtype.Timestamptz
	QualifiedAt           pgtype.Timestamptz
	MatchedAt             pgtype.Timestamptz
	RejectedAt            pgtype.Timestamptz
	CancelledAt           pgtype.Timestamptz
	ClosedAt              pgtype.Timestamptz
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

type BuyerBriefAttachment struct {
	ID               int64
	BuyerBriefID     int64
	ObjectKey        string
	OriginalFileName *string
	MimeType         *string
	SizeBytes        *int64
	Sha256           *string
	UploadedAt       pgtype.Timestamptz
}

type BuyerBriefItem struct {
	ID                int64
	BuyerBriefID      int64
	CategoryID        int64
	EstimatedQuantity int32
	ColorsNote        *string
	SizeBreakdownNote *string
	MaterialNote      *string
	HasTechpack       *bool
	HasPattern        *bool
	PrintingNote      *string
	PackagingNote     *string
	QualityNote       *string
	CreatedAt         pgtype.Timestamptz
}

type BuyerBriefStatusHistory struct {
	ID           int64
	BuyerBriefID int64
	FromStatus   *BriefStatus
	ToStatus     BriefStatus
	ChangedBy    *int64
	Note         *string
	ChangedAt    pgtype.Timestamptz
}

type CapabilityAvailability struct {
	ID                     int64
	ProfileCapabilityID    int64
	Status                 AvailabilityStatus
	EarliestSampleDate     pgtype.Date
	EarliestProductionDate pgtype.Date
	Capacity30DaysMin      *int32
	Capacity30DaysMax      *int32
	Capacity60DaysMin      *int32
	Capacity60DaysMax      *int32
	Source                 string
	ConfirmedBy            *int64
	ConfirmedAt            pgtype.Timestamptz
	ValidUntil             pgtype.Timestamptz
	Note                   *string
	CreatedAt              pgtype.Timestamptz
}

type Category struct {
	ID        int64
	Slug      string
	NameVi    string
	ParentID  *int64
	IsActive  bool
	SortOrder int32
	CreatedAt pgtype.Timestamptz
}

type Collection struct {
	ID                int64
	Slug              string
	Title             string
	Description       *string
	SelectionCriteria *string
	EditorialContent  *string
	CoverUrl          *string
	ProvinceCode      *string
	CategoryID        *int64
	IsPublished       bool
	PublishedAt       pgtype.Timestamptz
	CreatedBy         *int64
	CreatedAt         pgtype.Timestamptz
	UpdatedAt         pgtype.Timestamptz
}

type CollectionItem struct {
	CollectionID  int64
	ProfileID     int64
	Position      int32
	EditorialNote *string
}

type CurrentCapabilityAvailability struct {
	ID                     int64
	ProfileCapabilityID    int64
	Status                 AvailabilityStatus
	EarliestSampleDate     pgtype.Date
	EarliestProductionDate pgtype.Date
	Capacity30DaysMin      *int32
	Capacity30DaysMax      *int32
	Capacity60DaysMin      *int32
	Capacity60DaysMax      *int32
	Source                 string
	ConfirmedBy            *int64
	ConfirmedAt            pgtype.Timestamptz
	ValidUntil             pgtype.Timestamptz
	Note                   *string
}

type District struct {
	ID           int64
	ProvinceCode string
	NameVi       string
	Slug         string
	IsActive     bool
	CreatedAt    pgtype.Timestamptz
}

type IdempotencyRecord struct {
	ID                  int64
	Scope               string
	KeyHash             string
	RequestHash         string
	ResourceType        *string
	ResourcePublicToken *string
	ResponseStatus      *int32
	CreatedAt           pgtype.Timestamptz
	ExpiresAt           pgtype.Timestamptz
}

type ImportBatch struct {
	ID          int64
	PublicToken string
	InputHash   string
	Status      string
	CreatedBy   *int64
	CreatedAt   pgtype.Timestamptz
	CommittedAt pgtype.Timestamptz
	ErrorNote   *string
}

type Lead struct {
	ID              int64
	PublicToken     string
	BuyerBriefID    int64
	ProfileID       int64
	BriefMatchID    *int64
	CurrentStatus   LeadStatus
	SentAt          pgtype.Timestamptz
	ViewedAt        pgtype.Timestamptz
	FirstResponseAt pgtype.Timestamptz
	QuotedAt        pgtype.Timestamptz
	SampleStartedAt pgtype.Timestamptz
	WonAt           pgtype.Timestamptz
	LostAt          pgtype.Timestamptz
	ExpiredAt       pgtype.Timestamptz
	AssignedTo      *int64
	CreatedAt       pgtype.Timestamptz
	UpdatedAt       pgtype.Timestamptz
}

type LeadOutcome struct {
	ID                     int64
	LeadID                 int64
	LostReason             *LeadLostReason
	QuotedAmountNote       *string
	SampleCompleted        *bool
	OrderConfirmed         *bool
	OrderQuantity          *int32
	ExpectedDeliveryDate   pgtype.Date
	ActualDeliveryDate     pgtype.Date
	DeliveredOnTime        *bool
	BuyerFeedbackPrivate   *string
	FactoryFeedbackPrivate *string
	OutcomeVerified        bool
	VerifiedBy             *int64
	VerifiedAt             pgtype.Timestamptz
	CreatedAt              pgtype.Timestamptz
	UpdatedAt              pgtype.Timestamptz
}

type LeadStatusHistory struct {
	ID         int64
	LeadID     int64
	FromStatus *LeadStatus
	ToStatus   LeadStatus
	ChangedBy  *int64
	Note       *string
	ChangedAt  pgtype.Timestamptz
}

type Profile struct {
	ID                    int64
	Slug                  string
	Kind                  ProfileKind
	Name                  string
	Tagline               *string
	Description           *string
	ProvinceCode          string
	DistrictID            *int64
	Address               *string
	Latitude              pgtype.Numeric
	Longitude             pgtype.Numeric
	EstablishedYear       *int16
	WorkerCount           *int32
	ProductionLineCount   *int32
	ContactName           *string
	ContactPhone          *string
	ContactZalo           *string
	ContactEmail          *string
	WebsiteUrl            *string
	FacebookUrl           *string
	VerificationLevel     VerificationLevel
	LastVerifiedAt        pgtype.Timestamptz
	CompletenessScore     int16
	Featured              bool
	Status                ProfileStatus
	SearchText            string
	ResponseRate          pgtype.Numeric
	MedianResponseMinutes *int32
	QuoteRate             pgtype.Numeric
	SampleRate            pgtype.Numeric
	OrderRate             pgtype.Numeric
	CreatedBy             *int64
	UpdatedBy             *int64
	CreatedAt             pgtype.Timestamptz
	UpdatedAt             pgtype.Timestamptz
}

type ProfileCapability struct {
	ID                          int64
	ProfileID                   int64
	CategoryID                  int64
	ProductionModel             ProductionModel
	UsualMinOrderQty            *int32
	UsualMaxOrderQty            *int32
	EstimatedMonthlyCapacityMin *int32
	EstimatedMonthlyCapacityMax *int32
	SampleSupported             bool
	UsualSampleLeadDaysMin      *int32
	UsualSampleLeadDaysMax      *int32
	UsualProductionLeadDaysMin  *int32
	UsualProductionLeadDaysMax  *int32
	MaterialsNote               *string
	MachineryNote               *string
	CapabilityNote              *string
	CapabilityVerifiedAt        pgtype.Timestamptz
	CapabilitySource            *string
	CreatedAt                   pgtype.Timestamptz
	UpdatedAt                   pgtype.Timestamptz
}

type ProfileContactEvent struct {
	ID           int64
	ProfileID    *int64
	BuyerBriefID *int64
	EventType    ContactEventType
	SessionHash  *string
	ReferrerUrl  *string
	LandingUrl   *string
	UtmSource    *string
	UtmMedium    *string
	UtmCampaign  *string
	CreatedAt    pgtype.Timestamptz
}

type ProfileDataRefresh struct {
	ID              int64
	ProfileID       int64
	Source          string
	RefreshedBy     *int64
	FieldsRefreshed []byte
	Note            *string
	RefreshedAt     pgtype.Timestamptz
}

type ProfileImage struct {
	ID           int64
	ProfileID    int64
	CategoryID   *int64
	Kind         ImageKind
	Url          string
	ThumbnailUrl *string
	Caption      *string
	AltText      *string
	SortOrder    int32
	IsPublic     bool
	CreatedAt    pgtype.Timestamptz
}

type ProfileReport struct {
	ID              int64
	ProfileID       int64
	ReporterName    *string
	ReporterContact *string
	Reason          string
	Status          string
	HandledBy       *int64
	HandledNote     *string
	CreatedAt       pgtype.Timestamptz
	HandledAt       pgtype.Timestamptz
}

type ProfileSlugRedirect struct {
	OldSlug   string
	ProfileID int64
	CreatedAt pgtype.Timestamptz
}

type Province struct {
	Code   string
	NameVi string
	Slug   string
}

type Review struct {
	ID                  int64
	ProfileID           int64
	LeadID              *int64
	AuthorUserID        *int64
	AuthorName          string
	AuthorEmail         *string
	AuthorPhone         *string
	RatingOverall       *int16
	RatingQuality       *int16
	RatingDelivery      *int16
	RatingCommunication *int16
	RatingIssueHandling *int16
	Title               *string
	Body                *string
	VerificationStatus  ReviewVerificationStatus
	VerificationMethod  *string
	VerificationNote    *string
	VerifiedBy          *int64
	VerifiedAt          pgtype.Timestamptz
	ProofObjectKey      *string
	SubmissionIpHash    *string
	Status              ReviewStatus
	ModerationNote      *string
	ModeratedBy         *int64
	ModeratedAt         pgtype.Timestamptz
	PublishedAt         pgtype.Timestamptz
	CreatedAt           pgtype.Timestamptz
	UpdatedAt           pgtype.Timestamptz
}

type User struct {
	ID        int64
	Email     *string
	Phone     *string
	Name      string
	Role      UserRole
	IsActive  bool
	CreatedAt pgtype.Timestamptz
	UpdatedAt pgtype.Timestamptz
}

type VerificationRecord struct {
	ID                int64
	ProfileID         int64
	Level             VerificationLevel
	Result            VerificationResult
	Scope             string
	Method            *string
	Note              *string
	ServicePaid       bool
	VerifiedBy        *int64
	VerifiedAt        pgtype.Timestamptz
	ValidUntil        pgtype.Timestamptz
	EvidenceObjectKey *string
	IsPublic          bool
}
