// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: profiles.sql

package sqlcgen

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countPublishedProfiles = `-- name: CountPublishedProfiles :one
SELECT count(*)
FROM profiles p
WHERE p.status = 'published'
  AND ($1::text IS NULL OR p.province_code = $1::text)
  AND ($2::bigint IS NULL OR p.district_id = $2::bigint)
  AND (
    (
      $3::bigint IS NULL
      AND $4::production_model IS NULL
      AND $5::boolean IS NULL
      AND $6::int IS NULL
    )
    OR EXISTS (
      SELECT 1
      FROM profile_capabilities pc
      WHERE pc.profile_id = p.id
        AND ($3::bigint IS NULL OR pc.category_id = $3::bigint)
        AND ($4::production_model IS NULL OR pc.production_model = $4::production_model)
        AND ($5::boolean IS NULL OR pc.sample_supported = $5::boolean)
        AND ($6::int IS NULL OR pc.usual_min_order_qty <= $6::int)
    )
  )
`

type CountPublishedProfilesParams struct {
	ProvinceCode    *string
	DistrictID      *int64
	CategoryID      *int64
	ProductionModel *ProductionModel
	SampleSupported *bool
	MaxMoq          *int32
}

// Đếm tổng cho phân trang — cùng điều kiện WHERE với ListPublishedProfiles.
func (q *Queries) CountPublishedProfiles(ctx context.Context, arg CountPublishedProfilesParams) (int64, error) {
	row := q.db.QueryRow(ctx, countPublishedProfiles,
		arg.ProvinceCode,
		arg.DistrictID,
		arg.CategoryID,
		arg.ProductionModel,
		arg.SampleSupported,
		arg.MaxMoq,
	)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getPublishedProfileBySlug = `-- name: GetPublishedProfileBySlug :one
SELECT p.id, p.slug, p.kind, p.name, p.tagline, p.description,
       p.province_code, p.district_id, p.address,
       p.contact_name, p.contact_phone, p.contact_zalo, p.contact_email,
       p.website_url, p.facebook_url,
       p.established_year, p.worker_count, p.production_line_count,
       p.verification_level, p.last_verified_at, p.featured
FROM profiles p
WHERE p.slug = $1 AND p.status = 'published'
`

type GetPublishedProfileBySlugRow struct {
	ID                  int64
	Slug                string
	Kind                ProfileKind
	Name                string
	Tagline             *string
	Description         *string
	ProvinceCode        string
	DistrictID          *int64
	Address             *string
	ContactName         *string
	ContactPhone        *string
	ContactZalo         *string
	ContactEmail        *string
	WebsiteUrl          *string
	FacebookUrl         *string
	EstablishedYear     *int16
	WorkerCount         *int32
	ProductionLineCount *int32
	VerificationLevel   VerificationLevel
	LastVerifiedAt      pgtype.Timestamptz
	Featured            bool
}

// Detail công khai — chỉ profile published.
func (q *Queries) GetPublishedProfileBySlug(ctx context.Context, slug string) (GetPublishedProfileBySlugRow, error) {
	row := q.db.QueryRow(ctx, getPublishedProfileBySlug, slug)
	var i GetPublishedProfileBySlugRow
	err := row.Scan(
		&i.ID,
		&i.Slug,
		&i.Kind,
		&i.Name,
		&i.Tagline,
		&i.Description,
		&i.ProvinceCode,
		&i.DistrictID,
		&i.Address,
		&i.ContactName,
		&i.ContactPhone,
		&i.ContactZalo,
		&i.ContactEmail,
		&i.WebsiteUrl,
		&i.FacebookUrl,
		&i.EstablishedYear,
		&i.WorkerCount,
		&i.ProductionLineCount,
		&i.VerificationLevel,
		&i.LastVerifiedAt,
		&i.Featured,
	)
	return i, err
}

const listPublishedProfiles = `-- name: ListPublishedProfiles :many
SELECT p.id, p.slug, p.kind, p.name, p.tagline,
       p.province_code, p.verification_level, p.featured
FROM profiles p
WHERE p.status = 'published'
  AND ($1::text IS NULL OR p.province_code = $1::text)
  AND ($2::bigint IS NULL OR p.district_id = $2::bigint)
  AND (
    (
      $3::bigint IS NULL
      AND $4::production_model IS NULL
      AND $5::boolean IS NULL
      AND $6::int IS NULL
    )
    OR EXISTS (
      SELECT 1
      FROM profile_capabilities pc
      WHERE pc.profile_id = p.id
        AND ($3::bigint IS NULL OR pc.category_id = $3::bigint)
        AND ($4::production_model IS NULL OR pc.production_model = $4::production_model)
        AND ($5::boolean IS NULL OR pc.sample_supported = $5::boolean)
        AND ($6::int IS NULL OR pc.usual_min_order_qty <= $6::int)
    )
  )
ORDER BY p.featured DESC, p.id DESC
LIMIT $8
OFFSET $7
`

type ListPublishedProfilesParams struct {
	ProvinceCode    *string
	DistrictID      *int64
	CategoryID      *int64
	ProductionModel *ProductionModel
	SampleSupported *bool
	MaxMoq          *int32
	PageOffset      int32
	PageSize        int32
}

type ListPublishedProfilesRow struct {
	ID                int64
	Slug              string
	Kind              ProfileKind
	Name              string
	Tagline           *string
	ProvinceCode      string
	VerificationLevel VerificationLevel
	Featured          bool
}

// List công khai: chỉ profile published. Filter capability bằng semi-join EXISTS
// (KHÔNG JOIN+DISTINCT) để phân trang/sort ổn định ở tầng profile (§12.6).
func (q *Queries) ListPublishedProfiles(ctx context.Context, arg ListPublishedProfilesParams) ([]ListPublishedProfilesRow, error) {
	rows, err := q.db.Query(ctx, listPublishedProfiles,
		arg.ProvinceCode,
		arg.DistrictID,
		arg.CategoryID,
		arg.ProductionModel,
		arg.SampleSupported,
		arg.MaxMoq,
		arg.PageOffset,
		arg.PageSize,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPublishedProfilesRow
	for rows.Next() {
		var i ListPublishedProfilesRow
		if err := rows.Scan(
			&i.ID,
			&i.Slug,
			&i.Kind,
			&i.Name,
			&i.Tagline,
			&i.ProvinceCode,
			&i.VerificationLevel,
			&i.Featured,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveProfileRedirect = `-- name: ResolveProfileRedirect :one
SELECT p.slug
FROM profile_slug_redirects r
JOIN profiles p ON p.id = r.profile_id
WHERE r.old_slug = $1
`

// old_slug -> canonical slug hiện tại (redirect 1 bước, §12.8).
func (q *Queries) ResolveProfileRedirect(ctx context.Context, oldSlug string) (string, error) {
	row := q.db.QueryRow(ctx, resolveProfileRedirect, oldSlug)
	var slug string
	err := row.Scan(&slug)
	return slug, err
}

const upsertProfileBySlug = `-- name: UpsertProfileBySlug :one
INSERT INTO profiles (slug, kind, name, tagline, province_code, status, featured)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (slug) DO UPDATE
  SET kind          = EXCLUDED.kind,
      name          = EXCLUDED.name,
      tagline       = EXCLUDED.tagline,
      province_code = EXCLUDED.province_code,
      status        = EXCLUDED.status,
      featured      = EXCLUDED.featured
RETURNING id
`

type UpsertProfileBySlugParams struct {
	Slug         string
	Kind         ProfileKind
	Name         string
	Tagline      *string
	ProvinceCode string
	Status       ProfileStatus
	Featured     bool
}

// Dùng cho seed demo — idempotent theo slug (slug đã publish là bất biến).
func (q *Queries) UpsertProfileBySlug(ctx context.Context, arg UpsertProfileBySlugParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertProfileBySlug,
		arg.Slug,
		arg.Kind,
		arg.Name,
		arg.Tagline,
		arg.ProvinceCode,
		arg.Status,
		arg.Featured,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertProfileRedirect = `-- name: UpsertProfileRedirect :exec
INSERT INTO profile_slug_redirects (old_slug, profile_id)
VALUES ($1, $2)
ON CONFLICT (old_slug) DO UPDATE SET profile_id = EXCLUDED.profile_id
`

type UpsertProfileRedirectParams struct {
	OldSlug   string
	ProfileID int64
}

func (q *Queries) UpsertProfileRedirect(ctx context.Context, arg UpsertProfileRedirectParams) error {
	_, err := q.db.Exec(ctx, upsertProfileRedirect, arg.OldSlug, arg.ProfileID)
	return err
}
