// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: provinces.sql

package sqlcgen

import (
	"context"
)

const getProvinceByCode = `-- name: GetProvinceByCode :one
SELECT code, name_vi, slug
FROM provinces
WHERE code = $1
`

func (q *Queries) GetProvinceByCode(ctx context.Context, code string) (Province, error) {
	row := q.db.QueryRow(ctx, getProvinceByCode, code)
	var i Province
	err := row.Scan(&i.Code, &i.NameVi, &i.Slug)
	return i, err
}

const listProvinces = `-- name: ListProvinces :many
SELECT code, name_vi, slug
FROM provinces
ORDER BY name_vi
`

// Danh sách tỉnh/thành cho filter và landing /locations/{province}.
func (q *Queries) ListProvinces(ctx context.Context) ([]Province, error) {
	rows, err := q.db.Query(ctx, listProvinces)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Province
	for rows.Next() {
		var i Province
		if err := rows.Scan(&i.Code, &i.NameVi, &i.Slug); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
